[template]
src = "../templates/backend/application.conf.tmpl"
dest = "/etc/extendedmind/backend/application.conf"
keys = [
    "/extendedmind/ha",
    "/extendedmind/backend/tokensecret",
    "/extendedmind/backend/signupmode",
    "/extendedmind/backend/mailgundomain",
    "/extendedmind/backend/mailgunkey",
    "/extendedmind/emailfrom",
    "/extendedmind/urlorigin"
]
