[template]
src = "/etc/confd/templates/application.conf.tmpl"
dest = "/etc/extendedmind/application.conf"
keys = [
    "/extendedmind/ha",
    "/extendedmind/backend/tokenSecret",
    "/extendedmind/backend/signUpMode",
    "/extendedmind/backend/mailgunKey",
    "/extendedmind/domain",
    "/extendedmind/emailFrom",
    "/extendedmind/urlPrefix",
    "/extendedmind/secureUrlPrefix"
]