apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backend-tick-hourly
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: extendedmind
            tier: backend
            role: tick
            project: backend
            group: org.extendedmind
        spec:
          containers:
            - name: backend-tick-hourly
              image: quay.io/extendedmind/tar-curl-rsync:tcr-5
              command: ["/usr/bin/curl"]
              args:
              - "-H"
              - "Content-Type: application/json"
              - "-d"
              - "{\"priority\":2}"
              - "--silent"
              - "backend.default.svc.cluster.local:8081/v2/tick"
          restartPolicy: Never
          resources:
            limits:
              memory: 10Mi
              cpu: 10m
  schedule: "10 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
