apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backend-tick-daily
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: extendedmind
            tier: backend
            role: tick
            project: backend
            group: org.extendedmind
        spec:
          containers:
            - name: backend-tick-daily
              image: quay.io/extendedmind/tar-curl-rsync:tcr-5
              command: ["/usr/bin/curl"]
              args:
              - "-d"
              - "'{\"priority\":3}'"
              - "-H"
              - "'Content-Type:application/json'"
              - "--silent"
              - "backend.default.svc.cluster.local:8081/v2/tick"
          restartPolicy: Never
  schedule: "0 0 * * *"
