apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backend-backup
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: extendedmind
            tier: backend
            role: backup
            project: backend
            group: org.extendedmind
        spec:
          containers:
            - name: backend-backup
              args:
              - "backend.default.svc.cluster.local"
              - {{ .Values.backup.location | quote }}
              - {{ .Values.backup.days | quote }}
              - {{ .Values.fsPreCommand | quote }}
              image: quay.io/extendedmind/backend-backup:{{ .Values.backendBackupVersion }}
              resources:
{{ toYaml .Values.backendBackupResources | indent 16 }}
{{ if or .Values.backendBackupHeapSize .Values.backup.tmpDir }}
              env:
{{ if .Values.backendBackupHeapSize }}
              - name: HEAP_SIZE
                value: {{ .Values.backendBackupHeapSize }}
{{ end }}
{{ if .Values.backup.tmpDir }}
              - name: BACKUP_TMPDIR
                value: {{ .Values.backup.tmpDir }}
{{ end }}
{{ end }}
{{ if or .Values.backup.hostPath .Values.backup.tmpDir }}
              volumeMounts:
{{ if .Values.backup.hostPath }}
              - name: backupdir
                mountPath: "/app/backend-backup-data"
{{ end }}
{{ if .Values.backup.tmpDir }}
              - name: tmpdir
                mountPath: "/app/backend-backup-tmp"
{{ end }}
{{ end }}
          restartPolicy: Never
{{ if or .Values.backup.hostPath .Values.backup.tmpDir }}
          volumes:
{{ if .Values.backup.hostPath }}
          - name: backupdir
            hostPath:
              path: {{ .Values.backup.hostPath }}
{{ end }}
{{ if .Values.backup.tmpDir }}
          - name: tmpdir
            hostPath:
              path: {{ .Values.backup.tmpDir }}
{{ end }}
{{ end }}
  schedule: '10 * * * *'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
