[workspace]
resolver = "2"

members = [
    "schema",
    "core",
    "hub",
    "server",
    "ui/common",
    "ui/wasm",
    "ui/disk",
    "ui/cli",
    "ui/android/jni",
]

exclude = [
    "third_party/cargo",
]
