[lib]
path = "src/lib.rs"

[package]
name = "extendedmind_ui_common"
version = "0.0.1"
edition = "2021"
license = "AGPL-3.0-only"
authors = ["Timo Tiuraniemi <timo.tiuraniemi@iki.fi>"]

[dependencies]
extendedmind_core = { path = "../../core" }
log = "0.4.14"
futures = "^0.3.5"
