[lib]
path = "src/lib.rs"

[package]
name = "extendedmind_engine"
version = "0.1.0"
edition = "2018"
licence = "AGPL-3.0-only"
authors = ["Timo Tiuraniemi <timo.tiuraniemi@iki.fi>"]

[dependencies]
extendedmind_schema_rust = { path = "../schema" }
automerge-frontend = { git = "https://github.com/ttiurani/automerge-rs.git", rev = "bb6e4b95569ddef775da01c2ced69c5641371bbf" }
serde_json = "1.0.59"
bytes = "0.5.0"
async-std = "1.9.0"
futures = "^0.3.5"
hypercore = { git = "https://github.com/datrs/hypercore", rev = "8d8cbef8a884a70e8d12d80968c1d97be2ceea0b" }
hypercore-protocol = { git = "https://github.com/ttiurani/hypercore-protocol-rs", rev = "7208fda866b8235992e988b0e9ed3e4edf6787d4" }
random-access-disk = "2.0.0"
random-access-storage = "4.0.0"
hex = "0.4"
anyhow = "1.0.28"
log = "0.4.14"
reusable-box-future = "0.2.0"
