[lib]
path = "src/lib.rs"

[package]
name = "extendedmind_engine"
version = "0.1.0"
edition = "2018"
licence = "AGPL-3.0-only"
authors = ["Timo Tiuraniemi <timo.tiuraniemi@iki.fi>"]

[dependencies]
extendedmind_schema_rust = { path = "../schema" }
automerge-frontend = { git = "https://github.com/ttiurani/automerge-rs.git", rev = "c4230c029b0e20328fe2f5606e5503ffcd2cc964" }
serde_json = "1.0.59"
hypercore = { git = "https://github.com/datrs/hypercore.git", rev = "97ba31844886a4672a0ea8df6412881048bba1cb" }
hypercore-protocol = { git = "https://github.com/ttiurani/hypercore-protocol-rs.git", branch = "master" }
