apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nfs-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: extendedmind
        tier: frontend
        role: nfs
        project: frontend-site
        version: "${project.version}"
        group: org.extendedmind.frontend
    spec:
      containers:
        - name: nfs-provisioner
          image: quay.io/kubernetes_incubator/nfs-provisioner:v1.0.8
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
            - name: rpcbind-udp
              containerPort: 111
              protocol: UDP
          securityContext:
            capabilities:
              add:
                - DAC_READ_SEARCH
                - SYS_RESOURCE
          args:
            - "-provisioner=extendedmind.org/nfs"
            - "-grace-period=10"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_NAME
              value: nfs-provisioner
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: exportdir
              mountPath: /export
{{ if .Values.nfs.hostPath }}
      volumes:
      - name: exportdir
        hostPath:
          path: {{ .Values.nfs.hostPath }}
{{ else if .Values.nfs.gcePd }}
        gcePersistentDisk:
          pdName: {{ .Values.nfs.gcePd }}
          fsType: ext4
{{ end }}
