kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared
  labels:
    project: frontend-site
    group: org.extendedmind.frontend
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "extendedmind-nfs"
  resources:
    requests:
      storage: {{ .Values.nfs.storageSize }}
