apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  labels:
    project: backend
    version: "${project.version}"
    group: org.extendedmind
type: Opaque
data:
  tokenSecret: {{ b64enc .Values.tokenSecret | quote }}
{{ if .Values.init }}
  {{ if .Values.init.adminUserPassword }}
  adminUserPassword: {{ b64enc .Values.init.adminUserPassword | quote }}
  {{ end }}
{{ end }}
