apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: backend-backup
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: extendedmind
            tier: backend
            role: backup
            project: backend
            version: ${project.version}
            group: org.extendedmind
        spec:
          containers:
            - name: backend-backup
              args:
              - /bin/sh
              - -c
              - date; echo Hello from the Kubernetes cluster
              image: quay.io/extendedmind/backend-backup:0-SNAPSHOT
          restartPolicy: OnFailure
  schedule: '0 * * * *'
