apiVersion: v1
kind: Secret
metadata:
  name: backend
  labels:
    project: backend
    version: ${project.version}
    group: org.extendedmind
type: Opaque
data:
  tokenSecret: {{ .Values.tokenSecret | quote }}
{{ if .Values.init }}
  {{ if .Values.init.adminUserPassword }}
  adminUserPassword: {{ .Values.init.adminUserPassword | quote }}
  {{ end }}
{{ end }}
