# External service named "backend" that exposes the API and backup ports
apiVersion: v1
kind: Service
metadata:
  labels:
    app: extendedmind
    tier: backend
    project: backend
    group: org.extendedmind
  name: backend
spec:
  ports:
  - port: 8081
    protocol: TCP
    name: api
  - port: 6362
    protocol: TCP
    name: backup
  selector:
    role: server
    project: backend
    group: org.extendedmind
