apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: backend-backup
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: extendedmind
            tier: backend
            role: backup
            project: backend
            version: ${project.version}
            group: org.extendedmind
        spec:
          containers:
            - name: backend-backup
              args:
              - "backend-external.default.svc.cluster.local"
              - {{ .Values.backup.location | quote }}
              - {{ .Values.backup.days | quote }}
              - {{ .Values.fsPreCommand | quote }}
              image: quay.io/extendedmind/backend-backup:0-SNAPSHOT
{{ if .Values.backup.hostPath }}
              volumeMounts:
              - name: backupdir
                mountPath: "/app/backend-backup-data"
{{ end }}
          restartPolicy: Never
{{ if .Values.backup.hostPath }}
          volumes:
          - name: backupdir
            hostPath:
              path: {{ .Values.backup.hostPath }}
{{ end }}
  schedule: '*/1 * * * *'
