operationMode: SINGLE
storageClass: ${extendedmind.dbStorageClass}
copyPreCommand: "${extendedmind.dbCopyPreCommand}"
restore:
  file: ${extendedmind.dbRestoreFile}
  hostPath: ${extendedmind.dbRestoreHostPath}
