kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.siteHostName }}
  labels:
    project: frontend-site
    group: org.extendedmind.frontend
spec:
  ports:
  - name: site
    port: 3000
  selector:
    role: server
    project: frontend-site
    group: org.extendedmind.frontend
