apiVersion: batch/v1
kind: Job
metadata:
  name: site-static-{{ .Values.siteBuildNumber }}{{ .Values.extraSiteStaticJobSuffix }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  template:
    metadata:
      labels:
        project: frontend-site
        group: org.extendedmind.frontend
    spec:
      restartPolicy: Never
      initContainers:
      - name: site-static-prepare
        image: quay.io/extendedmind/tar-curl-rsync:tcr-5
        command: ["/bin/bash"]
        args:
        - "-c"
        - "mkdir -p /app/site-public/extendedmind && chown -R 1000:1000 /app/site-public/extendedmind"
        volumeMounts:
        - name: publicdir
          mountPath: /app/site-public
      containers:
      - name: site-static
        image: quay.io/{{ .Values.quayIoOrg }}/site-static:{{ .Values.siteStaticVersion }}
        volumeMounts:
        - name: publicdir
          mountPath: /app/site-public
          subPath: extendedmind
      volumes:
      - name: publicdir
        persistentVolumeClaim:
          claimName: shared
