kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared
  labels:
    project: shared
    group: org.extendedmind
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: {{ .Values.nfs.volumeSize }}
