apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: {{ .Values.nginxReplicas }}
  template:
    metadata:
      labels:
        app: extendedmind
        tier: frontend
        role: proxy
        project: frontend-site
        version: ${project.version}
        group: org.extendedmind.frontend
    spec:
      initContainers:
      - name: nginx-etc-init
        image: quay.io/{{ .Values.quayIoOrg }}/etc-init:${project.version}
        volumeMounts:
        - name: enableddir
          mountPath: "/etc/nginx/sites-enabled"
      containers:
      - name: nginx
        image: quay.io/extendedmind/nginx:nginx-1.13.0-1
        ports:
        - name: web
          containerPort: 8008
        volumeMounts:
        - name: enableddir
          mountPath: "/etc/nginx/sites-enabled"
        - name: publicdir
          mountPath: /app/site-public
          readOnly: true
          subPath: extendedmind
      volumes:
      - name: enableddir
        emptyDir: {}
      - name: publicdir
        persistentVolumeClaim:
          claimName: shared
