kind: Service
apiVersion: v1
metadata:
  name: site
  labels:
    project: frontend-site
    version: ${project.version}
    group: org.extendedmind.frontend
spec:
  ports:
  - name: site
    port: 3000
  selector:
    role: server
    project: frontend-site
    version: ${project.version}
    group: org.extendedmind.frontend
