{{ if .Values.useCronJobs }}
# CronJobs are alpha features until Kubernetes 1.7,
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: sync-folder
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: extendedmind
            tier: frontend
            role: sync
            project: frontend-site
            group: org.extendedmind.frontend
        spec:
          containers:
            - name: sync-site
              image: quay.io/extendedmind/sync-folder:{{ .Values.syncFolderVersion }}
              args:
              - "TODO"
{{ if .Values.sync.hostPath }}
              volumeMounts:
              - name: sourcedir
                mountPath: "/app/sync-source"
{{ end }}
          restartPolicy: Never
{{ if .Values.sync.hostPath }}
          volumes:
          - name: sourcedir
            hostPath:
              path: {{ .Values.sync.hostPath }}
{{ end }}
  schedule: '*/1 * * * *'

{{ else }}
# As a workaround, create a normal deployment that runs cron inside the docker image
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend-cron-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: extendedmind
        tier: frontend
        role: cron
        project: backend
        group: org.extendedmind
    spec:
      containers:
      - name: frontend-cron
        image: quay.io/extendedmind/sync-folder:{{ .Values.syncFolderVersion }}
        command: ["/bin/bash"]
        args:
        - "-c"
        - "mkdir /etc/periodic/1min && echo \"#!/bin/sh\n/app/sync-folder/sync-folder.sh {{ .Values.sync.source }} /app/site-public/extendedmind/files {{ .Values.fsPreCommand }} > /var/log/site-sync.log\" > /etc/periodic/1min/site-sync && echo \"#!/bin/sh\n{{ .Values.sync.extra1minJobContent }}\" {{ .Values.sync.extra1minJobPipe }} && chmod a+x /etc/periodic/1min/* && (crontab -l ; echo \"*/1     *       *       *       *       run-parts /etc/periodic/1min\") | crontab - && crond -l 8 -f -d 8"
        volumeMounts:
        - name: publicdir
          mountPath: /app/site-public
{{ if .Values.sync.hostPath }}
        - name: sourcedir
          mountPath: "/app/sync-source"
{{ end }}
      volumes:
      - name: publicdir
        persistentVolumeClaim:
          claimName: shared
{{ if .Values.sync.hostPath }}
      - name: sourcedir
        hostPath:
          path: {{ .Values.sync.hostPath }}
{{ end }}
{{ end }}
