[lib]
path = "src/lib.rs"

[package]
name = "extendedmind_schema_rust"
version = "0.0.1"
edition = "2021"
license = "AGPL-3.0-only"
authors = ["Timo Tiuraniemi <timo.tiuraniemi@iki.fi>"]
build = "build.rs"

[dependencies]
capnp = "0.14.11"
