[lib]
path = "target/src/lib.rs"

[package]
name = "extendedmind_schema_rust"
version = "0.1.0"
authors = ["Timo Tiuraniemi <timo.tiuraniemi@iki.fi>"]

[dependencies]
serde = "=1.0.116"
serde_derive = "=1.0.116"
serde_json = "=1.0.58"
