kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: db
  labels:
    project: environment
    group: org.extendedmind
provisioner: {{ .Values.db.provisioner }}
{{ if .Values.db.type }}
parameters:
  type: {{ .Values.db.type }}
{{ end }}
