kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: files
  labels:
    project: environment
    group: org.extendedmind
provisioner: {{ .Values.files.provisioner }}
{{ if .Values.files.type }}
parameters:
  type: {{ .Values.files.type }}
{{ end }}
