[package]
name = "extendedmind_hub"
version = "0.1.0"
edition = "2018"
licence = "AGPL-3.0-only"
authors = ["Timo Tiuraniemi <timo.tiuraniemi@iki.fi>"]

# [dependencies]

[dependencies]
extendedmind_engine = { path = "../engine" }
fern = "0.6.0"
log = "0.4.11"
anyhow = "1.0.33"
chrono = { version = "0.4.19" }
futures = "^0.3.5"
async-std = { version = "1.6.2", features = ["unstable"] }
tide = "0.16.0"
tide-websockets = "0.4.0"
tide-compress = "0.9.0"
moka = { version = "0.8.4", default-features = false, features = ["atomic64", "future"] }
async-tungstenite = { version = "0.13.1", features = ["async-std-runtime"] }
async-trait = "0.1.51"
ctrlc = { version = "3.0", features = ["termination"] }
async-ctrlc = { version = "1.2.0", features = ["stream"] }
clap = { version = "3.0.0-rc.5", features = ["derive"] }
derivative = "2.2.0"
