siteBuildNumber: "${buildNumber}"
siteStaticVersion: "${project.version}"
siteVersion: "${project.version}"
quayIoOrg: "extendedmind"
extraSiteStaticJobSuffix: ""
siteHostName: "site"
urlOrigin: "http://localhost:8008"
frontendReplicas: 1
