siteBuildNumber: "${buildNumber}"
siteStaticVersion: "${project.version}"
siteVersion: "${project.version}"
syncFolderVersion: "${project.version}"
quayIoOrg: "extendedmind"
extraSiteStaticJobSuffix: ""
siteHostName: "site"
urlOrigin: "http://localhost:8008"
frontendReplicas: 1
sync:
  # For testing purposes, this syncs all css static assets to the /files path
  source: "/app/site-public/extendedmind/assets/static"
  cronSchedule: "*/1 * * * *"
frontendSiteResources: {}
frontendSyncResources: {}
