# Default to one node implementation
# Other options are HA and HA_BOOTSTRAP and 3 replicas.
operationMode: SINGLE
replicas: 1

# Default to not using a pre command but instead doing backup/restore
# using the local filestystem. Other option is "gsutil" for
# google bucket save/restore.
fsPreCommand: ""
backup:
  days: 14
  frequency: hourly
  location: /app/backend-backup-data

# Default to insecure value: token does not actually contain any
# sensitive informatino anyway, so encrypting it wiht this is 
# not a security problem
tokenSecret: "01234567890123456789012345678901"

# Signing up is available and users get all latest features by
# default
signUpMethod: "ON"
signUpMode: "ALFA"

# Email settings:
emailProvider: "DUMMY"
# If the above is MAILGUN, the values below need to be set
mailgunDomain: ""
mailgunApiKey: ""
# This needs to be set when actually sending emails via mailgun
emailFrom: "example <example@example.com>"

# Set this to e.g. http://yourdomain.com if you have a domain
urlOrigin: "http://localhost"

# Default values for the UI
ui: "{\"powered\": true, \"help\": false}"
