backendDiscoveryVersion: "${project.version}"
backendRestoreVersion: "${project.version}"
backendVersion: "${project.version}"

# Default to non-secure token secret. This is not actually
# a major security problem as the token does not contain
# sensitive information – might as well be unencrypted as
# well. Encryption might be useful only for DOS mitigation.
tokenSecret: "01234567890123456789012345678901"
ui: "{\\\"powered\\\":true,\\\"help\\\":false}"

# Default to not using a pre command but instead doing backup/restore
# using the local filestystem. Other option is "gsutil" for
# google bucket save/restore.
fsPreCommand: ""
backup:
  days: 14
  frequency: hourly
  location: /app/backend-backup-data
